import type {
  BusinessProfile,
  Conversation,
  Listing,
  Message,
  Notification,
  Offer,
  Profile,
  Report,
  Transaction,
  VerificationRequest,
} from "../types";

/**
 * Seed dataset powering demo mode.
 *
 * Everything here is fictional test data. Financials, patent numbers and
 * company names are illustrative and must not be read as real filings or
 * real trading records.
 */

const now = Date.now();
const days = (n: number) => new Date(now - n * 86_400_000).toISOString();
const ahead = (n: number) => new Date(now + n * 86_400_000).toISOString();

export const DEMO_PROFILES: Profile[] = [
  {
    id: "u-admin",
    full_name: "Ana Petrova",
    avatar_url: null,
    headline: "BizHub platform administrator",
    bio: "Reviews listings, verification requests and reports.",
    country: "Bulgaria",
    role: "admin",
    is_verified: true,
    verification_status: "verified",
    is_blocked: false,
    premium_tier: "pro",
    created_at: days(420),
  },
  {
    id: "u-demo",
    full_name: "Demo User",
    avatar_url: null,
    headline: "Founder — exploring acquisitions",
    bio: "Signed in as the demo account. Buys and sells on the platform.",
    country: "Bulgaria",
    role: "user",
    is_verified: true,
    verification_status: "verified",
    is_blocked: false,
    premium_tier: "premium",
    created_at: days(96),
  },
  {
    id: "u-marek",
    full_name: "Marek Kowalski",
    avatar_url: null,
    headline: "Serial SaaS builder, 3 exits",
    bio: "Builds and sells bootstrapped B2B SaaS. Based in Warsaw.",
    country: "Poland",
    role: "user",
    is_verified: true,
    verification_status: "verified",
    is_blocked: false,
    premium_tier: "premium",
    created_at: days(310),
  },
  {
    id: "u-sofia",
    full_name: "Sofia Lindqvist",
    avatar_url: null,
    headline: "Cleantech researcher & patent holder",
    bio: "Materials science PhD. Licenses filtration and storage IP.",
    country: "Sweden",
    role: "user",
    is_verified: true,
    verification_status: "verified",
    is_blocked: false,
    premium_tier: "free",
    created_at: days(275),
  },
  {
    id: "u-diego",
    full_name: "Diego Ramos",
    avatar_url: null,
    headline: "E-commerce operator, 8 stores",
    bio: "Buys, scales and flips DTC brands across the EU.",
    country: "Spain",
    role: "user",
    is_verified: false,
    verification_status: "pending",
    is_blocked: false,
    premium_tier: "free",
    created_at: days(140),
  },
  {
    id: "u-amara",
    full_name: "Amara Okafor",
    avatar_url: null,
    headline: "Senior product designer",
    bio: "10 years designing B2B dashboards and marketplace UX.",
    country: "United Kingdom",
    role: "user",
    is_verified: true,
    verification_status: "verified",
    is_blocked: false,
    premium_tier: "free",
    created_at: days(200),
  },
  {
    id: "u-lukas",
    full_name: "Lukas Meyer",
    avatar_url: null,
    headline: "Robotics engineer",
    bio: "Industrial automation. Holds two granted EP patents.",
    country: "Germany",
    role: "user",
    is_verified: true,
    verification_status: "verified",
    is_blocked: false,
    premium_tier: "free",
    created_at: days(180),
  },
  {
    id: "u-yuki",
    full_name: "Yuki Tanaka",
    avatar_url: null,
    headline: "Growth marketer — paid acquisition",
    bio: "Scales paid channels for marketplaces and SaaS.",
    country: "Singapore",
    role: "user",
    is_verified: false,
    verification_status: "none",
    is_blocked: false,
    premium_tier: "free",
    created_at: days(64),
  },
  {
    id: "u-ivan",
    full_name: "Ivan Georgiev",
    avatar_url: null,
    headline: "Full-stack developer",
    bio: "Next.js, Postgres, payments. Available part-time.",
    country: "Bulgaria",
    role: "user",
    is_verified: true,
    verification_status: "verified",
    is_blocked: false,
    premium_tier: "free",
    created_at: days(150),
  },
  {
    id: "u-clara",
    full_name: "Clara Dubois",
    avatar_url: null,
    headline: "M&A lawyer, tech transactions",
    bio: "Advises on share purchase agreements and IP assignment.",
    country: "France",
    role: "user",
    is_verified: true,
    verification_status: "verified",
    is_blocked: false,
    premium_tier: "premium",
    created_at: days(230),
  },
  {
    id: "u-spam",
    full_name: "Quick Profits Ltd",
    avatar_url: null,
    headline: "Guaranteed returns",
    bio: "Account flagged by users and under review.",
    country: "United Arab Emirates",
    role: "user",
    is_verified: false,
    verification_status: "rejected",
    is_blocked: true,
    premium_tier: "free",
    created_at: days(12),
  },
];

/** Shorthand so each listing below stays readable. */
type L = Omit<Listing, "slug"> & { slug?: string };

const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

const base = {
  currency: "EUR",
  is_verified: false,
  is_featured: false,
  featured_until: null,
  boosted_until: null,
  cover_url: null,
  gallery: [] as string[],
  documents: [] as Listing["documents"],
  rejection_reason: null,
  status: "active" as const,
};

const raw: L[] = [
  // ---------------------------------------------------------------- businesses
  {
    ...base,
    id: "l-inboxly",
    owner_id: "u-marek",
    kind: "business",
    category_slug: "saas",
    title: "Inboxly — B2B email warm-up SaaS",
    summary:
      "Bootstrapped deliverability tool with 412 paying teams and 94% gross margin.",
    description:
      "Inboxly warms up cold-outreach mailboxes so sales teams land in the primary inbox. Launched in 2021, profitable since month 9, and run by a team of two.\n\nRevenue is 100% recurring across monthly and annual plans. Churn has held at 3.1% monthly for the last four quarters. Acquisition is 70% organic (SEO + a comparison-content engine) and 30% affiliate.\n\nThe stack is Next.js, Postgres and a Go worker fleet. Infrastructure runs at roughly €1,900/month. No investor obligations, no debt, clean cap table.",
    country: "Poland",
    price_cents: 42_000_000,
    deal_types: ["purchase"],
    is_verified: true,
    is_featured: true,
    featured_until: ahead(5),
    views_count: 3184,
    saves_count: 212,
    metrics: {
      annual_revenue_cents: 21_600_000,
      monthly_revenue_cents: 1_800_000,
      annual_expenses_cents: 7_200_000,
      monthly_profit_cents: 1_200_000,
      annual_profit_cents: 14_400_000,
      customers: 412,
      team_size: 2,
    },
    attributes: {
      business_model: "Subscription (SaaS)",
      year_founded: 2021,
      website: "https://inboxly.example.com",
      socials: [{ label: "LinkedIn", url: "https://linkedin.com/company/example" }],
      reason_for_selling:
        "Founders are moving full-time onto a new infrastructure product and want a clean handover.",
      assets_included: [
        "Source code and repositories",
        "Customer base and subscriptions",
        "Domain and brand assets",
        "SEO content library (340 articles)",
        "Documented handover + 60 days support",
      ],
      is_online: true,
    },
    documents: [
      { name: "P&L 2023–2025.pdf", path: "demo/inboxly-pl.pdf", visibility: "after_offer" },
      { name: "Churn cohort analysis.xlsx", path: "demo/inboxly-churn.xlsx", visibility: "on_request" },
    ],
    created_at: days(9),
    published_at: days(9),
  },
  {
    ...base,
    id: "l-nordic-supp",
    owner_id: "u-diego",
    kind: "business",
    category_slug: "e-commerce",
    title: "Nordic Supply Co — DTC outdoor gear brand",
    summary:
      "Four-year-old Shopify brand, €1.4M trailing revenue, 38% repeat purchase rate.",
    description:
      "Nordic Supply sells packable outdoor equipment to customers across Scandinavia and Germany. Inventory is held with a 3PL in Rotterdam and included in the sale at cost.\n\nThe brand has 61,000 email subscribers and a 38% repeat purchase rate. Paid social is the main channel at a blended 2.9x ROAS.\n\nSale includes all supplier relationships, three exclusive manufacturing agreements and remaining stock valued at €96,000.",
    country: "Spain",
    price_cents: 68_000_000,
    deal_types: ["purchase"],
    views_count: 1902,
    saves_count: 128,
    metrics: {
      annual_revenue_cents: 140_000_000,
      monthly_revenue_cents: 11_600_000,
      annual_expenses_cents: 117_000_000,
      monthly_profit_cents: 1_900_000,
      annual_profit_cents: 23_000_000,
      customers: 24_800,
      team_size: 5,
    },
    attributes: {
      business_model: "DTC e-commerce",
      year_founded: 2021,
      website: "https://nordicsupply.example.com",
      reason_for_selling: "Owner is consolidating into a single larger brand in the portfolio.",
      assets_included: [
        "Shopify store and theme",
        "€96,000 inventory at cost",
        "Supplier and 3PL contracts",
        "61k email list and flows",
        "Social accounts (94k followers)",
      ],
      is_online: true,
    },
    created_at: days(21),
    published_at: days(21),
  },
  {
    ...base,
    id: "l-routeplan",
    owner_id: "u-marek",
    kind: "business",
    category_slug: "mobile-apps",
    title: "RoutePlan — cycling navigation app",
    summary: "iOS + Android app, 180k installs, freemium with 4.2% conversion.",
    description:
      "RoutePlan builds elevation-aware routes for road and gravel cyclists. 180,000 lifetime installs, 22,000 monthly actives and 940 paying subscribers on a €4.99/month plan.\n\nThe app is feature-complete and needs roughly four hours of maintenance a week. Map data comes from OpenStreetMap so there are no licensing fees.",
    country: "Poland",
    price_cents: 9_500_000,
    deal_types: ["purchase"],
    views_count: 864,
    saves_count: 57,
    metrics: {
      annual_revenue_cents: 5_600_000,
      monthly_revenue_cents: 468_000,
      annual_expenses_cents: 1_100_000,
      monthly_profit_cents: 375_000,
      annual_profit_cents: 4_500_000,
      customers: 940,
      team_size: 1,
    },
    attributes: {
      business_model: "Freemium subscription",
      year_founded: 2020,
      website: "https://routeplan.example.com",
      reason_for_selling: "Focusing on the main SaaS business.",
      assets_included: ["App Store + Play listings", "Source code", "Brand and domain"],
      is_online: true,
    },
    created_at: days(31),
    published_at: days(31),
  },
  {
    ...base,
    id: "l-bakery",
    owner_id: "u-demo",
    kind: "business",
    category_slug: "local-businesses",
    title: "Sofia artisan bakery — two locations",
    summary: "Established 2016, two city-centre sites, long leases, stable local trade.",
    description:
      "A well-regarded artisan bakery with two locations in central Sofia. Both leases run to 2031 with fixed escalation.\n\nEleven staff including two head bakers who intend to stay. Equipment was fully renewed in 2023. Wholesale accounts with four local restaurants make up 18% of revenue.",
    country: "Bulgaria",
    price_cents: 18_000_000,
    deal_types: ["purchase"],
    is_verified: true,
    views_count: 611,
    saves_count: 39,
    metrics: {
      annual_revenue_cents: 42_000_000,
      monthly_revenue_cents: 3_500_000,
      annual_expenses_cents: 35_400_000,
      monthly_profit_cents: 550_000,
      annual_profit_cents: 6_600_000,
      customers: 0,
      team_size: 11,
    },
    attributes: {
      business_model: "Retail + wholesale",
      year_founded: 2016,
      reason_for_selling: "Owner is relocating abroad.",
      assets_included: ["Equipment", "Both leases", "Recipes and supplier list", "Staff contracts"],
      is_online: false,
    },
    created_at: days(44),
    published_at: days(44),
  },
  {
    ...base,
    id: "l-pixelforge",
    owner_id: "u-amara",
    kind: "business",
    category_slug: "agencies",
    title: "PixelForge — product design agency",
    summary: "Six-person remote design studio with three retainer clients.",
    description:
      "PixelForge has run since 2019 with a fully remote team across the UK and Portugal. Three retainer clients account for €18,400/month of predictable revenue, with project work on top.\n\nThe founder will stay through a three-month transition. All contractor relationships transfer.",
    country: "United Kingdom",
    price_cents: 31_000_000,
    deal_types: ["purchase"],
    is_featured: true,
    featured_until: ahead(3),
    views_count: 1244,
    saves_count: 81,
    metrics: {
      annual_revenue_cents: 62_000_000,
      monthly_revenue_cents: 5_100_000,
      annual_expenses_cents: 48_000_000,
      monthly_profit_cents: 1_160_000,
      annual_profit_cents: 14_000_000,
      customers: 9,
      team_size: 6,
    },
    attributes: {
      business_model: "Retainer + project services",
      year_founded: 2019,
      website: "https://pixelforge.example.com",
      reason_for_selling: "Founder is moving into an in-house leadership role.",
      assets_included: ["Client contracts", "Team and contractors", "Brand", "Case-study library"],
      is_online: true,
    },
    created_at: days(6),
    published_at: days(6),
  },
  {
    ...base,
    id: "l-devnews",
    owner_id: "u-ivan",
    kind: "business",
    category_slug: "content-businesses",
    title: "DevWeekly — developer newsletter, 84k subscribers",
    summary: "Weekly newsletter monetised through sponsorships. 46% open rate.",
    description:
      "DevWeekly has published every Tuesday since 2019. 84,000 subscribers, 46% open rate, sponsor slots booked eleven weeks out at €2,400 per issue.\n\nProduction takes about six hours a week. Sponsor pipeline and rate card included.",
    country: "Bulgaria",
    price_cents: 24_000_000,
    deal_types: ["purchase"],
    views_count: 977,
    saves_count: 74,
    metrics: {
      annual_revenue_cents: 11_500_000,
      monthly_revenue_cents: 958_000,
      annual_expenses_cents: 1_900_000,
      monthly_profit_cents: 800_000,
      annual_profit_cents: 9_600_000,
      customers: 22,
      team_size: 1,
    },
    attributes: {
      business_model: "Sponsorship / advertising",
      year_founded: 2019,
      reason_for_selling: "Taking a full-time engineering role.",
      assets_included: ["Subscriber list", "ESP account", "Archive and domain", "Sponsor pipeline"],
      is_online: true,
    },
    created_at: days(17),
    published_at: days(17),
  },
  {
    ...base,
    id: "l-fleetiq",
    owner_id: "u-lukas",
    kind: "business",
    category_slug: "technology-businesses",
    title: "FleetIQ — telematics hardware + platform",
    summary: "Vehicle-tracking hardware with recurring platform fees. 2,300 devices live.",
    description:
      "FleetIQ sells a tracking device paired with a fleet-management dashboard. 2,300 devices are active across 84 commercial fleets, each paying €9/device/month.\n\nHardware is manufactured under contract in Germany with a validated second source. Firmware, PCB designs and the platform are all included.",
    country: "Germany",
    price_cents: 95_000_000,
    deal_types: ["purchase"],
    is_verified: true,
    views_count: 1421,
    saves_count: 103,
    metrics: {
      annual_revenue_cents: 38_000_000,
      monthly_revenue_cents: 3_170_000,
      annual_expenses_cents: 20_000_000,
      monthly_profit_cents: 1_500_000,
      annual_profit_cents: 18_000_000,
      customers: 84,
      team_size: 7,
    },
    attributes: {
      business_model: "Hardware + recurring platform fee",
      year_founded: 2018,
      website: "https://fleetiq.example.com",
      reason_for_selling: "Shareholders want liquidity after seven years.",
      assets_included: ["Firmware and PCB designs", "Manufacturing contracts", "Platform", "Customer contracts"],
      is_online: false,
    },
    created_at: days(52),
    published_at: days(52),
  },
  {
    ...base,
    id: "l-pending-biz",
    owner_id: "u-diego",
    kind: "business",
    category_slug: "startups",
    title: "MealPrep Pro — meal-kit subscription (pre-revenue)",
    summary: "Awaiting moderation. Submitted for review three days ago.",
    description:
      "Pre-revenue meal-kit startup with a finished MVP, 340 waitlist signups and a signed kitchen partnership.",
    country: "Spain",
    price_cents: 3_500_000,
    deal_types: ["purchase"],
    status: "pending",
    views_count: 0,
    saves_count: 0,
    metrics: { team_size: 2 },
    attributes: { business_model: "Subscription", year_founded: 2025, is_online: true },
    created_at: days(3),
    published_at: null,
  },

  // ------------------------------------------------------------------ patents
  {
    ...base,
    id: "l-membrane",
    owner_id: "u-sofia",
    kind: "patent",
    category_slug: "water-technology",
    title: "Low-fouling graphene-oxide filtration membrane",
    summary:
      "Granted EP patent. Cuts backwash frequency by ~40% in municipal water treatment.",
    description:
      "A composite membrane using an aligned graphene-oxide interlayer that resists organic fouling. Bench and pilot testing at a municipal plant showed a 38–43% reduction in backwash cycles at equivalent flux.\n\nThe patent is granted in the EP region and pending in the US. The holder is open to an outright assignment of rights or to exclusive licensing by territory.\n\nA full technical dossier, pilot data and prosecution history are available to serious parties after an NDA.",
    country: "Sweden",
    price_cents: 3_000_000,
    deal_types: ["purchase", "license_exclusive", "license_non_exclusive"],
    is_verified: true,
    is_featured: true,
    featured_until: ahead(6),
    views_count: 2041,
    saves_count: 164,
    metrics: {},
    attributes: {
      patent_number: "EP3421876B1",
      jurisdiction: "European Patent Office (EP)",
      patent_status: "Granted",
      rights_holder: "Lindqvist Materials AB",
      filing_date: "2019-03-14",
      technology_field: "Membrane filtration / water treatment",
      license_price_cents: 200_000,
      license_period: "year",
      deal_types: ["purchase", "license_exclusive", "license_non_exclusive"],
    },
    documents: [
      { name: "Granted specification (public).pdf", path: "demo/ep3421876.pdf", visibility: "public" },
      { name: "Pilot test dataset.pdf", path: "demo/pilot.pdf", visibility: "after_offer" },
    ],
    created_at: days(14),
    published_at: days(14),
  },
  {
    ...base,
    id: "l-gripper",
    owner_id: "u-lukas",
    kind: "patent",
    category_slug: "robotics",
    title: "Adaptive soft gripper for mixed-SKU picking",
    summary: "Granted DE + EP. Handles 40–2,400g items without tool changes.",
    description:
      "A pneumatically actuated soft gripper with a compliant sensing skin that adapts grip force to item deformability. Designed for warehouse picking cells handling mixed SKUs.\n\nRights are held personally by the inventor. Non-exclusive licences are available per production line; an exclusive licence is available by sector.",
    country: "Germany",
    price_cents: 12_000_000,
    deal_types: ["purchase", "license_non_exclusive"],
    is_verified: true,
    views_count: 1180,
    saves_count: 92,
    metrics: {},
    attributes: {
      patent_number: "DE102021114552B4",
      jurisdiction: "Germany (DPMA), EP validated",
      patent_status: "Granted",
      rights_holder: "Lukas Meyer",
      filing_date: "2021-06-04",
      technology_field: "Robotics / end effectors",
      license_price_cents: 850_000,
      license_period: "year",
      deal_types: ["purchase", "license_non_exclusive"],
    },
    created_at: days(28),
    published_at: days(28),
  },
  {
    ...base,
    id: "l-battery",
    owner_id: "u-sofia",
    kind: "patent",
    category_slug: "energy",
    title: "Sodium-ion cathode coating process (application pending)",
    summary:
      "Application filed, not yet granted. Improves cycle life in sodium-ion cells.",
    description:
      "A wet-coating process for sodium-ion cathodes that reduced capacity fade to 8% over 1,000 cycles in laboratory cells.\n\nThis is a pending application, not a granted patent. The listing is marked accordingly and the platform has verified the application number and filing date only — no assessment of whether the application will be granted, and none of its commercial value.",
    country: "Sweden",
    price_cents: 1_800_000,
    deal_types: ["purchase", "license_non_exclusive"],
    views_count: 743,
    saves_count: 48,
    metrics: {},
    attributes: {
      patent_number: "SE2350412-7",
      jurisdiction: "Sweden (PRV)",
      patent_status: "Application pending",
      rights_holder: "Lindqvist Materials AB",
      filing_date: "2023-04-11",
      technology_field: "Battery materials",
      license_price_cents: 120_000,
      license_period: "year",
      deal_types: ["purchase", "license_non_exclusive"],
    },
    created_at: days(38),
    published_at: days(38),
  },
  {
    ...base,
    id: "l-vision",
    owner_id: "u-lukas",
    kind: "patent",
    category_slug: "ai",
    title: "On-device defect detection — licence only",
    summary: "Quantised vision model + method claim. Non-exclusive licences from €4,800/yr.",
    description:
      "A method for running surface-defect detection on embedded hardware under 2W, combined with a trained model and a calibration procedure for new production lines.\n\nThe rights holder is not selling the underlying rights — only non-exclusive annual licences are offered.",
    country: "Germany",
    price_cents: 0,
    deal_types: ["license_non_exclusive"],
    views_count: 522,
    saves_count: 31,
    metrics: {},
    attributes: {
      patent_number: "EP4102391A1",
      jurisdiction: "European Patent Office (EP)",
      patent_status: "Granted",
      rights_holder: "Meyer Automation GmbH",
      filing_date: "2020-11-02",
      technology_field: "Computer vision / industrial QA",
      license_price_cents: 480_000,
      license_period: "year",
      deal_types: ["license_non_exclusive"],
    },
    created_at: days(46),
    published_at: days(46),
  },

  // ----------------------------------------------------------- digital assets
  {
    ...base,
    id: "l-domain",
    owner_id: "u-demo",
    kind: "digital_asset",
    category_slug: "domains",
    title: "hiredesk.io — premium 8-letter .io domain",
    summary: "Clean history, registered 2014, no trademark conflicts found.",
    description:
      "Short, pronounceable and directly relevant to HR and recruiting products. Registered since 2014 with no prior site content and no spam history.\n\nTransfer is via registrar push, typically completed within 48 hours.",
    country: "Remote / Global",
    price_cents: 1_450_000,
    deal_types: ["purchase"],
    views_count: 486,
    saves_count: 44,
    metrics: {},
    attributes: { assets_included: ["Domain transfer", "Registrar push assistance"] },
    created_at: days(11),
    published_at: days(11),
  },
  {
    ...base,
    id: "l-boilerplate",
    owner_id: "u-ivan",
    kind: "digital_asset",
    category_slug: "source-code-projects",
    title: "Next.js marketplace boilerplate + licence",
    summary: "Production-ready starter: auth, listings, offers, Stripe Connect wiring.",
    description:
      "A complete marketplace starter in Next.js and Postgres: authentication, listing CRUD, offers, messaging and a Stripe Connect integration ready to enable.\n\nSold as an unlimited internal-use licence, not an exclusive transfer of the codebase.",
    country: "Bulgaria",
    price_cents: 89_000,
    deal_types: ["license_non_exclusive"],
    views_count: 1832,
    saves_count: 210,
    metrics: {},
    attributes: {
      tech_stack: ["Next.js", "TypeScript", "Postgres", "Tailwind"],
      license_price_cents: 89_000,
      license_period: "one-time",
    },
    created_at: days(24),
    published_at: days(24),
  },
  {
    ...base,
    id: "l-brieflyai",
    owner_id: "u-yuki",
    kind: "digital_asset",
    category_slug: "ai-tools",
    title: "BrieflyAI — meeting summariser (micro-SaaS)",
    summary: "€1,240 MRR, 310 paying users, runs on one small server.",
    description:
      "A single-purpose tool that turns meeting transcripts into structured summaries and action items. 310 paying users at €3.99/month.\n\nOperating cost is roughly €180/month including model inference. No employees.",
    country: "Singapore",
    price_cents: 4_400_000,
    deal_types: ["purchase"],
    is_featured: true,
    featured_until: ahead(2),
    views_count: 1607,
    saves_count: 139,
    metrics: {
      monthly_revenue_cents: 124_000,
      annual_revenue_cents: 1_488_000,
      monthly_profit_cents: 106_000,
      annual_profit_cents: 1_272_000,
      customers: 310,
      team_size: 1,
    },
    attributes: {
      business_model: "Subscription",
      year_founded: 2024,
      tech_stack: ["Python", "FastAPI", "Postgres"],
      monthly_users: 2_100,
      is_online: true,
    },
    created_at: days(4),
    published_at: days(4),
  },
  {
    ...base,
    id: "l-apiplug",
    owner_id: "u-marek",
    kind: "digital_asset",
    category_slug: "apis",
    title: "VAT validation API — EU-wide, 99.98% uptime",
    summary: "Metered API with 46 business customers on annual contracts.",
    description:
      "Validates and caches EU VAT registrations with a normalised response format. Handles roughly 4.2M calls a month.\n\nRuns on two small instances behind a CDN. Customer contracts renew annually with a 91% renewal rate.",
    country: "Poland",
    price_cents: 7_800_000,
    deal_types: ["purchase"],
    views_count: 692,
    saves_count: 51,
    metrics: {
      monthly_revenue_cents: 310_000,
      annual_revenue_cents: 3_720_000,
      annual_profit_cents: 2_900_000,
      customers: 46,
      team_size: 1,
    },
    attributes: { business_model: "Metered API", year_founded: 2022, is_online: true },
    created_at: days(35),
    published_at: days(35),
  },

  // ---------------------------------------------------------------- services
  {
    ...base,
    id: "s-amara",
    owner_id: "u-amara",
    kind: "service",
    category_slug: "designers",
    title: "Product design for B2B SaaS and marketplaces",
    summary: "End-to-end product design: research, UX, UI systems. From €650/day.",
    description:
      "I design B2B products that people use for hours a day — dashboards, admin tools and marketplace flows.\n\nTypical engagement is a two-week discovery followed by a design system and shipped screens. I work directly with your engineers in the repo where useful.",
    country: "United Kingdom",
    price_cents: 65_000,
    deal_types: ["purchase"],
    is_verified: true,
    views_count: 1290,
    saves_count: 88,
    metrics: {},
    attributes: {
      skills: ["Product design", "Design systems", "UX research", "Figma", "Webflow"],
      experience_years: 10,
      rate_unit: "day",
      portfolio: [
        { title: "Fintech dashboard redesign", url: "https://example.com/case-1" },
        { title: "Marketplace onboarding", url: "https://example.com/case-2" },
      ],
    },
    created_at: days(19),
    published_at: days(19),
  },
  {
    ...base,
    id: "s-ivan",
    owner_id: "u-ivan",
    kind: "service",
    category_slug: "developers",
    title: "Full-stack development — Next.js, Postgres, payments",
    summary: "Ships production features. Available 20h/week. €55/hour.",
    description:
      "Nine years building web products. I take a feature from spec to production including migrations, tests and deploy.\n\nStrongest on Next.js, Postgres, Supabase and payment integrations (Stripe, Adyen).",
    country: "Bulgaria",
    price_cents: 5_500,
    deal_types: ["purchase"],
    is_verified: true,
    views_count: 1512,
    saves_count: 112,
    metrics: {},
    attributes: {
      skills: ["Next.js", "TypeScript", "Postgres", "Supabase", "Stripe"],
      experience_years: 9,
      rate_unit: "hour",
    },
    created_at: days(22),
    published_at: days(22),
  },
  {
    ...base,
    id: "s-clara",
    owner_id: "u-clara",
    kind: "service",
    category_slug: "lawyers",
    title: "M&A and IP transaction counsel",
    summary: "Share purchase agreements, asset deals, IP assignment. €280/hour.",
    description:
      "Qualified in France, advising on technology M&A and intellectual property transactions across the EU.\n\nI review or draft SPAs, asset purchase agreements, patent assignments and licence agreements. Engagements are governed by a separate letter of engagement; nothing on this platform constitutes legal advice until that is signed.",
    country: "France",
    price_cents: 28_000,
    deal_types: ["purchase"],
    is_verified: true,
    views_count: 806,
    saves_count: 67,
    metrics: {},
    attributes: {
      skills: ["M&A", "IP licensing", "Due diligence", "Contract drafting"],
      experience_years: 14,
      rate_unit: "hour",
    },
    created_at: days(30),
    published_at: days(30),
  },
  {
    ...base,
    id: "s-yuki",
    owner_id: "u-yuki",
    kind: "service",
    category_slug: "marketing",
    title: "Paid acquisition for marketplaces",
    summary: "Meta, Google and TikTok. Retainer from €2,400/month.",
    description:
      "I run paid acquisition for two-sided marketplaces where supply and demand need different creative.\n\nRetainer covers strategy, creative direction, media buying and weekly reporting. Ad spend is billed separately by the platforms.",
    country: "Singapore",
    price_cents: 240_000,
    deal_types: ["purchase"],
    views_count: 934,
    saves_count: 58,
    metrics: {},
    attributes: {
      skills: ["Meta Ads", "Google Ads", "TikTok Ads", "Creative testing", "Analytics"],
      experience_years: 7,
      rate_unit: "month",
    },
    created_at: days(26),
    published_at: days(26),
  },

  // ---------------------------------------------------------------- partners
  {
    ...base,
    id: "p-logistics",
    owner_id: "u-diego",
    kind: "partner",
    category_slug: "operating-partner",
    title: "Looking for an operating partner — EU last-mile logistics",
    summary:
      "Contracts secured in two cities. Need a partner to run operations. €40k commitment.",
    description:
      "I have signed last-mile delivery contracts with two regional retailers in Spain and need an operating partner to build and run the fleet.\n\nI cover commercial and customer relationships. The partner runs operations, hiring and dispatch. Equity is 50/50 after the capital contribution is matched.",
    country: "Spain",
    price_cents: 0,
    deal_types: ["purchase"],
    views_count: 612,
    saves_count: 41,
    metrics: {},
    attributes: {
      investment_required_cents: 4_000_000,
      commitment: "Full-time",
      remote: false,
      skills: ["Operations", "Fleet management", "Hiring"],
      experience_years: 5,
    },
    created_at: days(13),
    published_at: days(13),
  },
  {
    ...base,
    id: "p-technical",
    owner_id: "u-yuki",
    kind: "partner",
    category_slug: "technical-partner",
    title: "Non-technical founder seeking technical co-founder",
    summary:
      "B2B procurement SaaS. 6 LOIs signed. Remote. Equity, no capital required.",
    description:
      "I have six letters of intent from mid-size manufacturers for a procurement tool and a clear product spec, but no engineering capability.\n\nLooking for a technical co-founder to build the first version. Meaningful equity, no capital contribution expected. Fully remote.",
    country: "Remote / Global",
    price_cents: 0,
    deal_types: ["purchase"],
    views_count: 1104,
    saves_count: 96,
    metrics: {},
    attributes: {
      investment_required_cents: 0,
      commitment: "Full-time or 3 days/week",
      remote: true,
      skills: ["Backend", "Product engineering", "B2B integrations"],
      experience_years: 4,
    },
    created_at: days(8),
    published_at: days(8),
  },

  // ------------------------------------------------------------------- ideas
  {
    ...base,
    id: "i-compliance",
    owner_id: "u-clara",
    kind: "idea",
    category_slug: "saas",
    title: "Compliance-document automation for small clinics",
    summary: "Researched concept with 22 customer interviews and a pricing model.",
    description:
      "Small private clinics spend 4–7 hours a month producing recurring compliance documentation. This is a validated concept package: 22 customer interviews, a feature map, a pricing model and a list of 40 warm leads who agreed to be contacted.\n\nThis is research and a plan — not a built product and not a guarantee of demand.",
    country: "France",
    price_cents: 180_000,
    deal_types: ["purchase"],
    views_count: 397,
    saves_count: 34,
    metrics: {},
    attributes: { business_model: "Subscription", is_online: true },
    created_at: days(41),
    published_at: days(41),
  },

  // ---------------------------------------------------------------- products
  {
    ...base,
    id: "pr-packaging",
    owner_id: "u-diego",
    kind: "product",
    category_slug: "packaging",
    title: "Compostable packaging supplier — EU, low MOQ",
    summary: "Certified compostable mailers and boxes. MOQ 500 units.",
    description:
      "Manufacturer of certified compostable mailers, boxes and void fill, shipping across the EU with a minimum order of 500 units and 12-day lead times.\n\nPrice shown is a representative per-1,000-unit rate; final pricing depends on specification.",
    country: "Netherlands",
    price_cents: 42_000,
    deal_types: ["purchase"],
    views_count: 288,
    saves_count: 19,
    metrics: {},
    attributes: { rate_unit: "1,000 units" },
    created_at: days(49),
    published_at: days(49),
  },

  // ---------------------------------------------------------------- ai tools
  {
    ...base,
    id: "ai-agent",
    owner_id: "u-ivan",
    kind: "ai_tool",
    category_slug: "agents",
    title: "Support-triage agent — self-hosted",
    summary: "Classifies and routes support tickets. Deploys to your own infra.",
    description:
      "A self-hosted agent that reads incoming support tickets, classifies intent, drafts a reply and routes anything uncertain to a human queue.\n\nSold as an annual licence including updates. Runs against your own model provider key so no ticket data leaves your infrastructure.",
    country: "Bulgaria",
    price_cents: 0,
    deal_types: ["license_non_exclusive"],
    views_count: 743,
    saves_count: 62,
    metrics: {},
    attributes: {
      license_price_cents: 180_000,
      license_period: "year",
      tech_stack: ["Python", "Docker"],
    },
    created_at: days(16),
    published_at: days(16),
  },

  // --------------------------------------------------------------- marketing
  {
    ...base,
    id: "m-seo",
    owner_id: "u-yuki",
    kind: "marketing",
    category_slug: "content-and-seo",
    title: "Programmatic SEO build-out for marketplaces",
    summary: "Template architecture, data pipeline and 500 pages shipped. From €6,000.",
    description:
      "A fixed-scope project that designs the page template architecture, builds the data pipeline and ships the first 500 programmatic pages with internal linking.\n\nResults depend on your domain authority and market — no ranking outcome is promised.",
    country: "Singapore",
    price_cents: 600_000,
    deal_types: ["purchase"],
    views_count: 421,
    saves_count: 27,
    metrics: {},
    attributes: { rate_unit: "project" },
    created_at: days(33),
    published_at: days(33),
  },

  // ------------------------------------------------------- moderation states
  {
    ...base,
    id: "l-rejected",
    owner_id: "u-spam",
    kind: "business",
    category_slug: "other",
    title: "Guaranteed 300% return crypto arbitrage business",
    summary: "Rejected by moderation.",
    description: "Listing promised guaranteed returns and could not evidence any of its claims.",
    country: "United Arab Emirates",
    price_cents: 500_000,
    deal_types: ["purchase"],
    status: "rejected",
    rejection_reason:
      "Guaranteed-return claims are not permitted, and the seller could not evidence the trading history provided.",
    views_count: 0,
    saves_count: 0,
    metrics: {},
    attributes: {},
    created_at: days(10),
    published_at: null,
  },
  {
    ...base,
    id: "l-sold",
    owner_id: "u-marek",
    kind: "business",
    category_slug: "websites",
    title: "RecipeVault — recipe site, 400k monthly visits",
    summary: "Sold in June. Kept visible as a completed transaction.",
    description: "Ad-monetised recipe site sold to a media group.",
    country: "Poland",
    price_cents: 15_000_000,
    deal_types: ["purchase"],
    status: "sold",
    views_count: 2210,
    saves_count: 96,
    metrics: { annual_revenue_cents: 8_400_000, annual_profit_cents: 6_100_000 },
    attributes: { business_model: "Advertising", year_founded: 2017, is_online: true },
    created_at: days(120),
    published_at: days(120),
  },
];

export const DEMO_LISTINGS: Listing[] = raw.map((l) => ({
  ...l,
  slug: l.slug ?? slugify(l.title),
}));

export const DEMO_BUSINESS_PROFILES: BusinessProfile[] = [
  {
    id: "bp-orbit",
    owner_id: "u-demo",
    name: "Orbit Labs",
    slug: "orbit-labs",
    logo_url: null,
    description:
      "We build internal tooling for logistics operators — dispatch boards, driver apps and route optimisation.",
    website: "https://orbitlabs.example.com",
    industry: "Logistics software",
    country: "Bulgaria",
    team: [
      { name: "Demo User", role: "Founder" },
      { name: "Ivan Georgiev", role: "Engineering" },
    ],
    products: ["Dispatch board", "Driver mobile app"],
    services: ["Custom integrations", "Onboarding & training"],
    goals:
      "Reach €40k MRR in 12 months and expand from two to five countries.",
    looking_for: ["Partners", "Developers", "Technology"],
    created_at: days(88),
  },
  {
    id: "bp-verde",
    owner_id: "u-sofia",
    name: "Verde Water",
    slug: "verde-water",
    logo_url: null,
    description:
      "Materials research company commercialising filtration technology for municipal and industrial water treatment.",
    website: "https://verdewater.example.com",
    industry: "Cleantech",
    country: "Sweden",
    team: [{ name: "Sofia Lindqvist", role: "Founder & CTO" }],
    products: ["GO-composite membrane"],
    services: ["Pilot deployments", "Technology licensing"],
    goals: "License the membrane technology into three EU markets.",
    looking_for: ["Partners", "Suppliers"],
    created_at: days(210),
  },
  {
    id: "bp-pixelforge",
    owner_id: "u-amara",
    name: "PixelForge Studio",
    slug: "pixelforge-studio",
    logo_url: null,
    description:
      "Remote product design studio working with B2B SaaS and marketplace teams across Europe.",
    website: "https://pixelforge.example.com",
    industry: "Design services",
    country: "United Kingdom",
    team: [
      { name: "Amara Okafor", role: "Design lead" },
      { name: "Two senior designers", role: "Design" },
    ],
    products: [],
    services: ["Product design", "Design systems", "UX research"],
    goals: "Move from project work to 80% retainer revenue.",
    looking_for: ["Employees", "Designers"],
    created_at: days(160),
  },
];

export const DEMO_OFFERS: Offer[] = [
  {
    id: "o-1",
    listing_id: "l-inboxly",
    buyer_id: "u-demo",
    seller_id: "u-marek",
    amount_cents: 36_000_000,
    deal_type: "purchase",
    message:
      "Serious buyer, funds available. Offering €360k based on a 2.5x profit multiple. Happy to move quickly on diligence.",
    status: "countered",
    parent_offer_id: null,
    created_at: days(5),
  },
  {
    id: "o-2",
    listing_id: "l-inboxly",
    buyer_id: "u-demo",
    seller_id: "u-marek",
    amount_cents: 39_500_000,
    deal_type: "purchase",
    message:
      "Thanks for the offer. I can meet you at €395k including the 60-day handover and the content library.",
    status: "pending",
    parent_offer_id: "o-1",
    created_at: days(4),
  },
  {
    id: "o-3",
    listing_id: "l-membrane",
    buyer_id: "u-diego",
    seller_id: "u-sofia",
    amount_cents: 180_000,
    deal_type: "license_non_exclusive",
    message:
      "Interested in a non-exclusive licence for the Iberian market. Can we discuss territory scope?",
    status: "pending",
    parent_offer_id: null,
    created_at: days(2),
  },
  {
    id: "o-4",
    listing_id: "l-bakery",
    buyer_id: "u-diego",
    seller_id: "u-demo",
    amount_cents: 15_500_000,
    deal_type: "purchase",
    message: "Offering €155k, subject to reviewing the lease agreements.",
    status: "pending",
    parent_offer_id: null,
    created_at: days(1),
  },
  {
    id: "o-5",
    listing_id: "l-brieflyai",
    buyer_id: "u-demo",
    seller_id: "u-yuki",
    amount_cents: 4_000_000,
    deal_type: "purchase",
    message: "€40k, cash, closing within two weeks.",
    status: "rejected",
    parent_offer_id: null,
    created_at: days(6),
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: "c-1",
    listing_id: "l-inboxly",
    buyer_id: "u-demo",
    seller_id: "u-marek",
    last_message_at: days(0.2),
  },
  {
    id: "c-2",
    listing_id: "l-membrane",
    buyer_id: "u-demo",
    seller_id: "u-sofia",
    last_message_at: days(1.4),
  },
  {
    id: "c-3",
    listing_id: "l-bakery",
    buyer_id: "u-diego",
    seller_id: "u-demo",
    last_message_at: days(0.9),
  },
];

export const DEMO_MESSAGES: Message[] = [
  {
    id: "m-1",
    conversation_id: "c-1",
    sender_id: "u-demo",
    body: "Hi Marek — impressive numbers. Could you share the churn breakdown by plan before I make a formal offer?",
    attachments: [],
    read_at: days(5),
    created_at: days(5.2),
  },
  {
    id: "m-2",
    conversation_id: "c-1",
    sender_id: "u-marek",
    body: "Of course. Annual plans churn at 1.4% monthly, monthly plans at 4.6%. I've attached the cohort file to the listing documents — you'll get access once we have an accepted offer.",
    attachments: [],
    read_at: days(5),
    created_at: days(5),
  },
  {
    id: "m-3",
    conversation_id: "c-1",
    sender_id: "u-demo",
    body: "That works. I've submitted €360k formally through the offer flow.",
    attachments: [],
    read_at: days(4.6),
    created_at: days(4.8),
  },
  {
    id: "m-4",
    conversation_id: "c-1",
    sender_id: "u-marek",
    body: "Countered at €395k. That includes the handover period and the full content library — I think it's fair given the organic traffic.",
    attachments: [],
    read_at: null,
    created_at: days(0.2),
  },
  {
    id: "m-5",
    conversation_id: "c-2",
    sender_id: "u-demo",
    body: "Hello Sofia — is the EP patent available for exclusive licence limited to Southeast Europe?",
    attachments: [],
    read_at: days(1.5),
    created_at: days(1.6),
  },
  {
    id: "m-6",
    conversation_id: "c-2",
    sender_id: "u-sofia",
    body: "Yes, territory-limited exclusivity is possible. Terms would be drafted by our respective lawyers — I can share the technical dossier under NDA first.",
    attachments: [],
    read_at: null,
    created_at: days(1.4),
  },
  {
    id: "m-7",
    conversation_id: "c-3",
    sender_id: "u-diego",
    body: "Are both leases transferable without landlord consent, or is consent required?",
    attachments: [],
    read_at: null,
    created_at: days(0.9),
  },
];

export const DEMO_FAVORITES: { user_id: string; listing_id: string; created_at: string }[] = [
  { user_id: "u-demo", listing_id: "l-membrane", created_at: days(3) },
  { user_id: "u-demo", listing_id: "l-fleetiq", created_at: days(7) },
  { user_id: "u-demo", listing_id: "s-amara", created_at: days(2) },
  { user_id: "u-demo", listing_id: "l-brieflyai", created_at: days(6) },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: "n-1",
    user_id: "u-demo",
    type: "offer_countered",
    title: "Counter-offer on Inboxly",
    body: "Marek Kowalski countered your €360,000 offer with €395,000.",
    link: "/dashboard/offers",
    is_read: false,
    created_at: days(0.2),
  },
  {
    id: "n-2",
    user_id: "u-demo",
    type: "message_received",
    title: "New message from Sofia Lindqvist",
    body: "Yes, territory-limited exclusivity is possible…",
    link: "/messages/c-2",
    is_read: false,
    created_at: days(1.4),
  },
  {
    id: "n-3",
    user_id: "u-demo",
    type: "offer_received",
    title: "New offer on Sofia artisan bakery",
    body: "Diego Ramos offered €155,000.",
    link: "/seller/offers",
    is_read: false,
    created_at: days(1),
  },
  {
    id: "n-4",
    user_id: "u-demo",
    type: "listing_approved",
    title: "Listing approved",
    body: "hiredesk.io is now live on the marketplace.",
    link: "/listing/l-domain",
    is_read: true,
    created_at: days(11),
  },
  {
    id: "n-5",
    user_id: "u-demo",
    type: "new_match",
    title: "New listing matches your search",
    body: "A SaaS business under €50,000 was just published.",
    link: "/businesses",
    is_read: true,
    created_at: days(4),
  },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: "t-1",
    listing_id: "l-sold",
    buyer_id: "u-diego",
    seller_id: "u-marek",
    amount_cents: 15_000_000,
    fee_bps: 1000,
    fee_cents: 1_500_000,
    net_cents: 13_500_000,
    status: "released",
    provider: "mock",
    created_at: days(58),
  },
  {
    id: "t-2",
    listing_id: "l-boilerplate",
    buyer_id: "u-demo",
    seller_id: "u-ivan",
    amount_cents: 89_000,
    fee_bps: 1000,
    fee_cents: 8_900,
    net_cents: 80_100,
    status: "released",
    provider: "mock",
    created_at: days(20),
  },
  {
    id: "t-3",
    listing_id: "l-vision",
    buyer_id: "u-diego",
    seller_id: "u-lukas",
    amount_cents: 480_000,
    fee_bps: 1000,
    fee_cents: 48_000,
    net_cents: 432_000,
    status: "paid",
    provider: "mock",
    created_at: days(9),
  },
  {
    id: "t-4",
    listing_id: "s-amara",
    buyer_id: "u-demo",
    seller_id: "u-amara",
    amount_cents: 325_000,
    fee_bps: 1000,
    fee_cents: 32_500,
    net_cents: 292_500,
    status: "pending",
    provider: "mock",
    created_at: days(2),
  },
];

export const DEMO_REPORTS: Report[] = [
  {
    id: "r-1",
    reporter_id: "u-marek",
    target_type: "listing",
    target_id: "l-rejected",
    reason: "Misleading claims",
    details: "Listing promises guaranteed returns with no evidence.",
    status: "resolved",
    created_at: days(10),
  },
  {
    id: "r-2",
    reporter_id: "u-amara",
    target_type: "user",
    target_id: "u-spam",
    reason: "Spam / solicitation",
    details: "Sent identical unsolicited investment pitches to several sellers.",
    status: "open",
    created_at: days(6),
  },
  {
    id: "r-3",
    reporter_id: "u-diego",
    target_type: "listing",
    target_id: "l-battery",
    reason: "Unverified patent claim",
    details: "Wants confirmation that the application status shown is accurate.",
    status: "reviewing",
    created_at: days(3),
  },
];

export const DEMO_VERIFICATIONS: VerificationRequest[] = [
  {
    id: "v-1",
    user_id: "u-diego",
    listing_id: null,
    kind: "seller",
    evidence: [
      { label: "Company registration", value: "ES-B87654321" },
      { label: "ID document", value: "Uploaded" },
    ],
    status: "pending",
    notes: null,
    created_at: days(4),
  },
  {
    id: "v-2",
    user_id: "u-sofia",
    listing_id: "l-battery",
    kind: "patent",
    evidence: [
      { label: "Application number", value: "SE2350412-7" },
      { label: "Filing receipt", value: "Uploaded" },
      { label: "Assignment record", value: "Uploaded" },
    ],
    status: "pending",
    notes: null,
    created_at: days(2),
  },
  {
    id: "v-3",
    user_id: "u-diego",
    listing_id: "l-nordic-supp",
    kind: "business",
    evidence: [
      { label: "Merchant statements", value: "12 months uploaded" },
      { label: "Domain ownership", value: "DNS TXT verified" },
    ],
    status: "pending",
    notes: null,
    created_at: days(1),
  },
];

/** The account used when browsing in demo mode. */
export const DEMO_CURRENT_USER_ID = "u-demo";
