import Link from "next/link";
import { redirect } from "next/navigation";
import { ChecklistPicker } from "@/components/checklist-picker";
import { MilestoneBoard } from "@/components/milestone-board";
import { Notice } from "@/components/ui";
import { getCurrentUser, getMilestones, getMyBusiness } from "@/lib/data";

export const metadata = { title: "Build plan" };

export default async function WorkspacePlanPage() {
  const me = await getCurrentUser();
  if (!me) redirect("/login");

  const business = await getMyBusiness(me.id);
  if (!business) return null;

  const milestones = await getMilestones(business.id);

  return (
    <div className="space-y-8">
      <MilestoneBoard milestones={milestones} />

      <ChecklistPicker />

      <div className="card bg-[var(--color-surface-2)] p-6 lg:p-8">
        <h2 className="display text-xl">Need the steps written for you?</h2>
        <p className="mt-2 max-w-2xl text-[0.9375rem] leading-relaxed text-[var(--color-ink-2)]">
          Describe your idea and Bizora drafts an indicative plan. You choose
          which steps to keep — they become editable steps in this checklist,
          not advice you have to follow.
        </p>
        <Link href="/start-a-business" className="btn btn-brand mt-5">
          Generate an indicative plan
        </Link>
      </div>

      <Notice tone="gold" title="A plan is not a guarantee">
        Steps generated by Bizora are a starting point for your own research.
        They are not financial, legal, tax or investment advice, and following
        them does not mean a business will succeed. Anything that depends on
        local law should be confirmed with a qualified professional in your
        country.
      </Notice>
    </div>
  );
}
